# Пропишем версию
version: '3'


# Перечислим сервисы
services:

    nginx:
        image: nginx:latest
        container_name: nginx-${COMPOSE_PROJECT_NAME}

        environment:
            - TZ=${PROJECT_TZ}

        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./etc/nginx:/etc/nginx/conf.d
            - ../logs:/var/log/nginx
            - ../htdocs:/var/www

        restart: unless-stopped

        links:
            - php

    mysql:

        image: mariadb:latest

        ports:
            - "${MYSQL_PORT}:3306"

        container_name: mysql-${COMPOSE_PROJECT_NAME}

        environment:
            - TZ=${PROJECT_TZ}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

        restart: unless-stopped

        volumes:
            - ./etc/mysql:/etc/mysql
            - ../mysql:/var/lib/mysql
            - ../logs:/var/log/


    php:

        build: ./etc/php

        container_name: php-fpm-${COMPOSE_PROJECT_NAME}

        environment:
              DB_HOST: ${MYSQL_HOST}
              DB_DATABASE: ${MYSQL_DATABASE}
              DB_USERNAME: ${MYSQL_USER}
              DB_PASSWORD: ${MYSQL_PASSWORD}    
              TZ: ${PROJECT_TZ}

        # extra_hosts:
        #     - "intranet.mydomain.com:172.18.74.8"

        volumes:
            - ../htdocs:/var/www
            - ../uploads:/mnt/uploads

        restart: unless-stopped

        links:
            - mysql



